version: '3'
services:
  redis:
    image: redis:redis-cache
    ports:
      - "6379:6379"
  postgres:
    image: postgres:rest-app
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data