name: Deploy Docker App to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug changed files
        run: git diff --name-only HEAD~1 HEAD

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_KEY }}" > ~/.ssh/aws_key.pem
          chmod 600 ~/.ssh/aws_key.pem
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Check if SRC folder has changed
        id: check_src
        run: |
          if git diff --name-only HEAD~1 HEAD | grep '^SRC/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Copy files to EC2
        if: steps.check_src.outputs.changed == 'true'
        run: |
          rsync -avz --delete --checksum -e "ssh -i ~/.ssh/aws_key.pem -o StrictHostKeyChecking=no" ./ ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}:/home/ubuntu/nuviora_backend

      - name: Deploy fastapi container via SSH
        if: steps.check_src.outputs.changed == 'true'
        run: |
          ssh -i ~/.ssh/aws_key.pem -o StrictHostKeyChecking=no ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            cd /home/ubuntu/nuviora_backend
            docker-compose build --no-cache fastapi
            docker-compose up -d fastapi
          EOF
