name: Deploy Docker App to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_KEY }}" > ~/.ssh/aws_key.pem
          chmod 600 ~/.ssh/aws_key.pem
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
      - name: Check if SRC folder has changed
        id: check_src
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^SRC/'; then
            echo "SRC_CHANGED=true" >> $GITHUB_ENV
          else
            echo "SRC_CHANGED=false" >> $GITHUB_ENV
          fi
    
      - name: Copy files to EC2
        if: env.SRC_CHANGED == 'true'
        run: |
          rsync -avz -e "ssh -i ~/.ssh/aws_key.pem" ./ ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}:/home/ubuntu/nuviora_backend

      - name: Deploy via SSH
        if: env.SRC_CHANGED == 'true'
        run: |
          ssh -i ~/.ssh/aws_key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            cd /home/ubuntu/nuviora_backend
            docker-compose build fastapi_app
            docker-compose up -d fastapi_app
          EOF
